### ISSUE TITLE
It also make TypeScript generics colorful

### ISSUE THREAD

**Issue by cytharubyscriptonrails** [jzmstrjp/vscode-color-the-tag-name#2]

**Comment by BoscoDomingo** [comment]
Can confirm. It's the reason I had to uninstall. I don't seem to recall any options to only enable on .tsx files, so all .ts files see their generics modified

**Comment by jzmstrjp** [comment]
Thank you. I try.

**Comment by BoscoDomingo** [comment]
No problem! Just add a filter for .ts files and it should work as expected ;)

[Line 81 of extension.ts](https://github.com/jzmstrjp/vscode-color-the-tag-name/blob/4f30d31b935bb687c576e1e94fd1580703dc5bb1/src/extension.ts#L81) seems like the perfect place to check

**Comment by yumemi-tokumoto** [comment]
Thanks.
I have released a modified version that excludes .ts files.

**Comment by thegroosalugg** [comment]
I am looking for the opposite of what is requested here. This extension highlights my HTML in JS, JSX and TSX, but not in TS. I would like it to also highlight my TS files as I am using template literals to write HTML code in TS files. Is there a way I can enable it?

**Comment by yumemi-tokumoto** [comment]
It might be helpful to add a feature where users can specify a list of file extensions to exclude.
