### ISSUE TITLE
Use theme's 'type' property (or give a configuration setting to force dark/light mode)

### ISSUE THREAD

**Issue by TheCarrotCR** [jzmstrjp/vscode-color-the-tag-name#4]
I've never learned how VS Code extensions works, but what I've got from your commits is that you trying to detect whether theme is dark or light by searching for a corresponding substring in theme's name (if I'm wrong then just ignore me I guess xd). Thing is, I'm using a Sepia Theme, which is named just "Sepia", so this approach is not working for it. I've done some research though, and apparently themes has an attribute named 'type' which is, atleast for that "Sepia" theme I'm using, has values of either 'light' or 'dark'. So I think you can try and somehow use this attribute as well.

Link to a mentioned theme, if you curious: https://github.com/ZYinMD/sepia/blob/master/themes/sepia.json

**Comment by yumemi-tokumoto** [comment]
Thank You! I Do!

**Comment by yumemi-tokumoto** [comment]
@TheCarrotCR 

I've modified it to switch based on the [theme's kind](https://code.visualstudio.com/api/references/vscode-api#ColorThemeKind)!

**Comment by TheCarrotCR** [comment]
Now it works with theme that I'm using, thanks very much!
